---
version: 21
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: mensual
  ignore:
  - dependency-name: observación*
    update-types:
    - version-update:semver-major
    - 111
  - dependency-name: búsqueda de nodo
    update-types:
    - 'actualización de versión: semver-major'
  - dependency-name: Ava
    update-types:
    - 'actualización de versión: semver-major'
  - dependency-name: regla de pelusa unificada
    update-types:
    - 'actualización de versión: semver-major'
  - dependency-name: unist-*
    update-types:
    - 'actualización de versión: semver-major'
- package-ecosystem: npm
  directory: "/funciones"
  schedule:
    interval: diario
  commit-message:
    prefix: "\U0001F4CC(funciones)"
